# Generated by Django 6.0 on 2026-01-11 21:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('icon', models.CharField(blank=True, max_length=64, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(max_length=256)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('last_links_checked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'providers',
                'indexes': [models.Index(fields=['is_active', 'name'], name='providers_is_acti_44bdee_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('canceled', 'Canceled'), ('trial', 'Trial'), ('expired', 'Expired')], db_index=True, default='active', max_length=10)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('payment_method_label', models.CharField(blank=True, max_length=64, null=True)),
                ('owner_note', models.CharField(blank=True, max_length=255, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('current_price_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_price_currency', models.CharField(max_length=3)),
                ('next_billing_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('billing_timezone', models.CharField(blank=True, max_length=64, null=True)),
                ('last_billed_at', models.DateTimeField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.category')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(max_length=3)),
                ('effective_from', models.DateTimeField(db_index=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('change_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('integration', 'Integration')], default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'price_history',
            },
        ),
        migrations.CreateModel(
            name='BillingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_unit', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=8)),
                ('period_interval', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('anchor_day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('anchor_weekday', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('grace_days', models.PositiveSmallIntegerField(default=0)),
                ('next_run_at', models.DateTimeField(db_index=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_schedules', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'billing_schedules',
            },
        ),
        migrations.CreateModel(
            name='ProviderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_index=True, default='GLOBAL', max_length=8)),
                ('platform', models.CharField(choices=[('web', 'Web'), ('ios', 'IOS'), ('android', 'Android'), ('desktop', 'Desktop'), ('tv', 'TV'), ('unknown', 'Unknown')], db_index=True, default='web', max_length=10)),
                ('link_type', models.CharField(choices=[('billing', 'Billing'), ('account', 'Account'), ('support', 'Support'), ('pricing', 'Pricing')], db_index=True, max_length=10)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='subscriptions.provider')),
            ],
            options={
                'db_table': 'provider_links',
                'indexes': [models.Index(fields=['provider', 'region', 'platform', 'link_type'], name='provider_li_provide_a61dd1_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'region', 'platform', 'link_type'), name='uniq_provider_region_platform_linktype')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_8d58fd_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'next_billing_at'], name='subscriptio_user_id_dc673b_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('current_price_amount__gte', 0)), name='subscription_current_price_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['subscription', '-effective_from'], name='price_histo_subscri_0a2ac1_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricehistory',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='price_history_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='pricehistory',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='price_history_effective_to_gt_from'),
        ),
        migrations.AddIndex(
            model_name='billingschedule',
            index=models.Index(fields=['subscription', 'is_current'], name='billing_sch_subscri_197bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='billingschedule',
            index=models.Index(fields=['is_current', 'next_run_at'], name='billing_sch_is_curr_582641_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingschedule',
            constraint=models.CheckConstraint(condition=models.Q(('period_interval__gte', 1)), name='billing_schedule_interval_gte_1'),
        ),
    ]
