# Generated by Django 6.0 on 2026-01-12 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingschedule',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='billingschedule',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
