# Generated by Django 6.0 on 2026-01-12 20:51

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_created_at_billingschedule_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='currency',
            field=models.CharField(max_length=3, validators=[utils.validators.validator_currency]),
        ),
        migrations.AlterField(
            model_name='providerlink',
            name='region',
            field=models.CharField(db_index=True, default='GLOBAL', max_length=8, validators=[utils.validators.validator_region]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_timezone',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[utils.validators.validator_timezone]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_price_currency',
            field=models.CharField(max_length=3, validators=[utils.validators.validator_currency]),
        ),
    ]
