# Generated by Django 6.0 on 2026-02-02 20:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_pricehistory_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerlink',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Заполняется только для manual-режима.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='currency',
            field=models.CharField(blank=True, help_text='Заполняется только для manual-режима.', max_length=3, null=True, validators=[utils.validators.validator_currency]),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='source',
            field=models.CharField(choices=[('verified', 'Verified'), ('manual', 'Manual'), ('import', 'Import')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_price_currency',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[utils.validators.validator_currency]),
        ),
        migrations.CreateModel(
            name='VerifiedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=128, null=True)),
                ('region', models.CharField(db_index=True, default='GLOBAL', max_length=8, validators=[utils.validators.validator_region])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(max_length=3, validators=[utils.validators.validator_currency])),
                ('period_unit', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=8)),
                ('period_interval', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('platform', models.CharField(choices=[('web', 'Web'), ('ios', 'IOS'), ('android', 'Android'), ('desktop', 'Desktop'), ('tv', 'TV'), ('unknown', 'Unknown')], db_index=True, default='web', max_length=10)),
                ('source', models.CharField(choices=[('admin', 'Admin'), ('api', 'API'), ('sync', 'Sync')], max_length=8)),
                ('valid_from', models.DateTimeField(db_index=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_price', to='subscriptions.provider')),
                ('source_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_price', to='subscriptions.providerlink')),
            ],
            options={
                'db_table': 'verified_prices',
            },
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='verified_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_history', to='subscriptions.verifiedprice'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(max_length=3, validators=[utils.validators.validator_currency])),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('sync', 'Sync')], default='manual', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.pricehistory')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-paid_at', '-created_at'],
                'indexes': [models.Index(fields=['subscription', 'paid_at'], name='subscriptio_subscri_89dc6c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='verifiedprice',
            index=models.Index(fields=['provider', 'region', 'currency', 'plan_name'], name='verified_pr_provide_513cd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='verifiedprice',
            constraint=models.UniqueConstraint(fields=('provider', 'region', 'currency', 'plan_name', 'valid_from'), name='verified_price_version'),
        ),
    ]
