# Generated by Django 6.0 on 2026-02-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_providerlink_last_checked_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='verifiedprice',
            name='verified_price_version',
        ),
        migrations.RemoveIndex(
            model_name='verifiedprice',
            name='verified_pr_provide_513cd3_idx',
        ),
        migrations.AddIndex(
            model_name='verifiedprice',
            index=models.Index(fields=['provider', 'plan_name', 'platform', 'region', 'currency', 'period_unit', 'period_interval'], name='verified_pr_provide_7b7861_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('subscription',), name='uniq_active_subscription_schedule'),
        ),
        migrations.AddConstraint(
            model_name='pricehistory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verified_price__isnull', False), ('amount__isnull', True), ('currency__isnull', True)), models.Q(('verified_price__isnull', True), ('amount__isnull', False), ('currency__isnull', False)), _connector='OR'), name='price_history_verified_or_manual'),
        ),
        migrations.AddConstraint(
            model_name='pricehistory',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('subscription',), name='uniq_active_subscription_price'),
        ),
        migrations.AddConstraint(
            model_name='verifiedprice',
            constraint=models.UniqueConstraint(fields=('provider', 'plan_name', 'platform', 'region', 'currency', 'period_unit', 'period_interval', 'valid_from'), name='verified_price_version'),
        ),
    ]
