# Generated by Django 6.0 on 2026-02-05 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_remove_verifiedprice_verified_price_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='source',
            field=models.CharField(choices=[('verified', 'Verified'), ('manual', 'Manual')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='verified_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='subscriptions.verifiedprice'),
        ),
        migrations.AlterField(
            model_name='verifiedprice',
            name='source_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_price', to='subscriptions.providerlink'),
        ),
    ]
