# Generated by Django 6.0 on 2026-02-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_pricehistory_source_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_subscri_13ad39_idx',
            old_name='subscriptio_subscri_89dc6c_idx',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
    ]
