# Generated by Django 6.0 on 2026-02-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_rename_subscriptio_subscri_89dc6c_idx_payments_subscri_13ad39_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='verifiedprice',
            name='verified_price_version',
        ),
        migrations.AddConstraint(
            model_name='verifiedprice',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('provider', 'plan_name', 'platform', 'region', 'currency', 'period_unit', 'period_interval', 'valid_from'), name='uniq_active_verified_price'),
        ),
    ]
