# Generated by Django 6.0 on 2026-02-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_remove_verifiedprice_verified_price_version_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='verifiedprice',
            name='uniq_active_verified_price',
        ),
        migrations.AddConstraint(
            model_name='verifiedprice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='verified_price_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='verifiedprice',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='verified_price_valid_to_gt_from'),
        ),
        migrations.AddConstraint(
            model_name='verifiedprice',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('provider', 'plan_name', 'platform', 'region', 'currency', 'period_unit', 'period_interval'), name='uniq_active_verified_price'),
        ),
    ]
