# Generated by Django 6.0 on 2026-03-24 19:00

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_remove_verifiedprice_uniq_active_verified_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingschedule',
            options={'verbose_name': 'График списания', 'verbose_name_plural': 'График списаний'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at', '-created_at'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'verbose_name': 'История цены', 'verbose_name_plural': 'История цен'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Провайдер', 'verbose_name_plural': 'Провайдеры'},
        ),
        migrations.AlterModelOptions(
            name='providerlink',
            options={'verbose_name': 'Ссылка провайдера', 'verbose_name_plural': 'Ссылки провайдера'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='verifiedprice',
            options={'verbose_name': 'Verified цена', 'verbose_name_plural': 'Verified цены'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_timezone',
            field=models.CharField(default='UTC', max_length=64, validators=[utils.validators.validator_timezone]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('canceled', 'Canceled'), ('trial', 'Trial'), ('delayed', 'Delayed'), ('expired', 'Expired')], db_index=True, default='active', max_length=10),
        ),
    ]
