# Generated by Django 6.0 on 2026-03-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_alter_billingschedule_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
