# Generated by Django 6.0.6 on 2026-07-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_subscription_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
