# Generated by Django 6.0.7 on 2026-07-15 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_alter_provider_description'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='workspaces.workspace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='ws_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='workspaces.workspacegroup'),
        ),
    ]
