# Generated by Django 6.0.8 on 2026-09-28 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_subscription_workspace_subscription_ws_group'),
        ('workspaces', '0002_remove_workspacegroup_wsg_parent_level_consistency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscriptio_user_id_8d58fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscriptio_user_id_dc673b_idx',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['owner', 'status'], name='subscriptio_owner_i_d25b56_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['owner', 'next_billing_at'], name='subscriptio_owner_i_c3a79f_idx'),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_shared',
        ),
    ]
