# Generated by Django 6.0.7 on 2026-07-15 00:49

import apps.workspaces.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(db_index=True, default=apps.workspaces.utils.gen_ws_code, editable=False, max_length=16, unique=True)),
                ('type', models.CharField(choices=[('personal', 'Personal'), ('team', 'Team'), ('organization', 'Organization')], db_index=True, default='personal', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated'), ('blocked', 'Blocked'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рабочее пространство',
                'verbose_name_plural': 'Рабочие пространства',
                'db_table': 'workspaces',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='workspaces.workspacegroup')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Группа / Отдел / Подразделение',
                'verbose_name_plural': 'Группы / Отделы / Подразделения',
                'db_table': 'workspace_groups',
                'ordering': ['workspace', 'level'],
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['status', 'type'], name='ws_status_type_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner', 'status'], name='ws_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['status', 'created_at'], name='ws_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('title', ''), _negated=True), models.Q(('slug', ''), _negated=True), models.Q(('code', ''), _negated=True)), name='ws_title_slug_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.CheckConstraint(condition=models.Q(('is_default', False), ('type', 'personal'), _connector='OR'), name='ws_default_must_be_personal'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('type', 'personal')), fields=('owner',), name='uniq_ws_default_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='uniq_ws_owner_slug'),
        ),
        migrations.AddIndex(
            model_name='workspacegroup',
            index=models.Index(fields=['workspace', 'is_active'], name='wsg_ws_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacegroup',
            index=models.Index(fields=['workspace', 'level', 'is_active'], name='wsg_ws_level_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacegroup',
            index=models.Index(fields=['parent', 'is_active'], name='wsg_parent_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacegroup',
            index=models.Index(fields=['workspace', 'slug'], name='wsg_ws_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacegroup',
            index=models.Index(fields=['workspace', 'title'], name='wsg_ws_title_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacegroup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('title', ''), _negated=True), models.Q(('slug', ''), _negated=True)), name='wsg_title_slug_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='workspacegroup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('level', 1), ('parent__isnull', True)), models.Q(('level__gt', 1), ('parent__isnull', False)), _connector='OR'), name='wsg_parent_level_consistency'),
        ),
        migrations.AddConstraint(
            model_name='workspacegroup',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='wsg_parent_not_self'),
        ),
        migrations.AddConstraint(
            model_name='workspacegroup',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('workspace', 'slug'), name='uniq_wsg_root_slug'),
        ),
        migrations.AddConstraint(
            model_name='workspacegroup',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'slug'), name='uniq_wsg_child_slug'),
        ),
    ]
