# Generated by Django 6.0.8 on 2026-09-28 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workspacegroup',
            name='wsg_parent_level_consistency',
        ),
        migrations.AlterField(
            model_name='workspacegroup',
            name='level',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
